<?php

namespace ContainerXnOUMlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GdS0O4yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GdS0O4y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GdS0O4y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customerSuccess' => ['privates', '.errored..service_locator.GdS0O4y.App\\Entity\\CustomerSuccess', NULL, 'Cannot autowire service ".service_locator.GdS0O4y": it references class "App\\Entity\\CustomerSuccess" but no such service exists.'],
        ], [
            'customerSuccess' => 'App\\Entity\\CustomerSuccess',
        ]);
    }
}
