<?php

namespace ContainerXnOUMlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerSuccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7wiH4Tw.App\Entity\CustomerSuccess' shared service.
     *
     * @return \App\Entity\CustomerSuccess
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7wiH4Tw": it references class "App\\Entity\\CustomerSuccess" but no such service exists.');
    }
}
