<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKTLb8be\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKTLb8be/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKTLb8be.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKTLb8be\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKTLb8be\App_KernelDevDebugContainer([
    'container.build_hash' => 'KTLb8be',
    'container.build_id' => '50c0272c',
    'container.build_time' => 1648133112,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKTLb8be');
