<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_axios_index_js-node_m-c1f3cb.js',
                'http://localhost:8080/build/app.js',
            ],
            'css' => [
                'http://localhost:8080/build/app.css',
            ],
        ],
    ],
],

]];
