<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Experts extends \App\Entity\Experts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'civilite', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'presentation', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'dateDesactivation', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'sousCategories', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'chemins', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'rendezVous', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'disponibilités', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'civilite', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'codePostal', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'presentation', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'dateDesactivation', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'sousCategories', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'chemins', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'rendezVous', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'disponibilités', '' . "\0" . 'App\\Entity\\Experts' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Experts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivilite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivilite', []);

        return parent::getCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivilite(string $civilite): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivilite', [$civilite]);

        return parent::setCivilite($civilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(string $codePostal): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$codePostal]);

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentation', []);

        return parent::getPresentation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentation(?string $presentation): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentation', [$presentation]);

        return parent::setPresentation($presentation);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDesactivation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDesactivation', []);

        return parent::getDateDesactivation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDesactivation(?\DateTimeInterface $dateDesactivation): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDesactivation', [$dateDesactivation]);

        return parent::setDateDesactivation($dateDesactivation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\App\Entity\Categories $category): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$category]);

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\App\Entity\Categories $category): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$category]);

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousCategories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousCategories', []);

        return parent::getSousCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addSousCategory(\App\Entity\SousCategories $sousCategory): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSousCategory', [$sousCategory]);

        return parent::addSousCategory($sousCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSousCategory(\App\Entity\SousCategories $sousCategory): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSousCategory', [$sousCategory]);

        return parent::removeSousCategory($sousCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getChemins(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChemins', []);

        return parent::getChemins();
    }

    /**
     * {@inheritDoc}
     */
    public function addChemin(\App\Entity\Chemins $chemin): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChemin', [$chemin]);

        return parent::addChemin($chemin);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChemin(\App\Entity\Chemins $chemin): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChemin', [$chemin]);

        return parent::removeChemin($chemin);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendezVous(): ?\App\Entity\RendezVous
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendezVous', []);

        return parent::getRendezVous();
    }

    /**
     * {@inheritDoc}
     */
    public function setRendezVous(?\App\Entity\RendezVous $rendezVous): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRendezVous', [$rendezVous]);

        return parent::setRendezVous($rendezVous);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibilités(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibilités', []);

        return parent::getDisponibilités();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibilités(?string $disponibilités): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibilités', [$disponibilités]);

        return parent::setDisponibilités($disponibilités);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entity\Users $user): \App\Entity\Experts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

}
