<?php

namespace ContainerKTLb8be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7wiH4TwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7wiH4Tw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7wiH4Tw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customerSuccess' => ['privates', '.errored..service_locator.7wiH4Tw.App\\Entity\\CustomerSuccess', NULL, 'Cannot autowire service ".service_locator.7wiH4Tw": it references class "App\\Entity\\CustomerSuccess" but no such service exists.'],
            'customerSuccessRepository' => ['privates', 'App\\Repository\\CustomerSuccessRepository', 'getCustomerSuccessRepositoryService', true],
        ], [
            'customerSuccess' => 'App\\Entity\\CustomerSuccess',
            'customerSuccessRepository' => 'App\\Repository\\CustomerSuccessRepository',
        ]);
    }
}
