<?php

namespace ContainerKTLb8be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerSuccessTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CustomerSuccessType' shared autowired service.
     *
     * @return \App\Form\CustomerSuccessType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CustomerSuccessType.php';

        return $container->privates['App\\Form\\CustomerSuccessType'] = new \App\Form\CustomerSuccessType();
    }
}
