#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index